"""Generate and validate the one ordered table of open work, over BACKLOG.md and BUGS.md.

Why this exists rather than a hand-maintained table: BACKLOG.md had sixteen rounds of numbered
lists and the same items kept recurring, because it recorded WHAT to do and never what doing it
would buy. The cheapest item won every time. On 2026-09-21 a session proposed a guard-tolerance fix
that changes zero coached turns ahead of a defect affecting forty.

Why it spans TWO files: `BUGS.md` holds 21 defects, 17 of them fixed, with root-cause writeups worth
keeping where they are. But the four that are still open were competing for the same attention as
backlog items while being invisible to the priority table. Merging the files would bury the defect
log; one index over both keeps a single ordered list without moving anything.

    python scripts/backlog_index.py            # rewrite the table in BACKLOG.md
    python scripts/backlog_index.py --check     # exit 1 if stale, or a field is missing

The table is GENERATED from the per-item fields rather than maintained beside them. Writing it twice
is the "two copies of one check handed different arguments" shape that has caused five defects in
this repo, most recently in the very script that measures the cause detector.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKLOG = ROOT / "BACKLOG.md"
BUGS = ROOT / "BUGS.md"

BEGIN = "<!-- BEGIN BACKLOG INDEX (generated by scripts/backlog_index.py - do not edit by hand) -->"
END = "<!-- END BACKLOG INDEX -->"

#: A BACKLOG heading is ACTIONABLE when it starts with one of these. Everything else in that file is
#: a record — a closed item, a decision kept for its reasoning, a narrative section — and records do
#: not get priorities. Em dash or hyphen, because both have been used.
ACTIONABLE = re.compile(r"^(#{2,3})\s+(TOP|OPEN)\s*[—-]\s*(.+?)\s*$")

#: A BUGS heading. Whether it needs metadata depends on its status, not on its title.
BUG_HEADING = re.compile(r"^###\s+(BUG-\d+)\s*:\s*(.+?)\s*$")

#: A bug is a RECORD when its status begins with FIXED, or it is superseded. "PARTIALLY FIXED" is
#: deliberately NOT matched: BUG-006 is partially fixed and still open, and a rule that keyed on the
#: word "FIXED" anywhere would have filed it as done.
BUG_CLOSED = re.compile(r"^\s*-\s+\*\*Status\*\*:\s*(FIXED|superseded)\b", re.IGNORECASE)

ANY_HEADING = re.compile(r"^#{1,6}\s+")

CATEGORIES = ("coaching", "instrumentation", "engine", "decision", "infra")
PRIORITIES = ("P1", "P2", "P3")
ID_RE = re.compile(r"^(?:B-\d{3}|BUG-\d+)$")

FIELD = re.compile(r"^\s*-\s+\*\*(Id|Category|Gives|Priority):\*\*\s*(.+?)\s*$")
REQUIRED = ("Id", "Category", "Gives", "Priority")


@dataclass(frozen=True)
class Item:
    source: str
    line: int
    ident: str
    kind: str
    title: str
    category: str
    gives: str
    priority: str


def _collapse(text: str) -> str:
    """One line, single-spaced — a table cell cannot contain a newline."""
    return " ".join(text.split())


def _fields_under(lines: list[str], start: int) -> dict[str, str]:
    """Read the metadata block directly under a heading.

    Fields must appear before any prose that is not a field and before the next heading, so a
    "**Gives:**" appearing later in the body cannot be mistaken for the item's own.
    """
    found: dict[str, str] = {}
    pending: str | None = None
    for raw in lines[start + 1 :]:
        if ANY_HEADING.match(raw):
            break
        m = FIELD.match(raw)
        if m:
            pending = m.group(1)
            found[pending] = m.group(2)
            continue
        if pending and raw.startswith("  ") and raw.strip():
            found[pending] += " " + raw.strip()
            continue
        if raw.strip():
            break
    return found


def _validate(found: dict[str, str], where: str, title: str, problems: list[str]) -> bool:
    missing = [f for f in REQUIRED if f not in found]
    if missing:
        problems.append(f"{where}: {title!r} is missing {', '.join(missing)}")
        return False
    ok = True
    if not ID_RE.match(found["Id"]):
        problems.append(f"{where}: {title!r} has Id {found['Id']!r}; expected B-001 form or BUG-nn")
        ok = False
    if found["Category"] not in CATEGORIES:
        problems.append(f"{where}: {title!r} has Category {found['Category']!r}, expected one of {CATEGORIES}")
        ok = False
    if found["Priority"] not in PRIORITIES:
        problems.append(f"{where}: {title!r} has Priority {found['Priority']!r}, expected one of {PRIORITIES}")
        ok = False
    return ok


def parse_backlog(text: str) -> tuple[list[Item], list[str]]:
    lines = text.splitlines()
    items: list[Item] = []
    problems: list[str] = []
    for i, line in enumerate(lines):
        m = ACTIONABLE.match(line)
        if not m:
            continue
        kind, title = m.group(2), m.group(3)
        found = _fields_under(lines, i)
        where = f"BACKLOG.md line {i + 1}"
        if not _validate(found, where, title, problems):
            continue
        items.append(
            Item(
                "backlog",
                i + 1,
                found["Id"],
                kind,
                title,
                found["Category"],
                _collapse(found["Gives"]),
                found["Priority"],
            )
        )
    return items, problems


def parse_bugs(text: str) -> tuple[list[Item], list[str]]:
    """Open bugs only. A bug whose status begins FIXED (or is superseded) is a record."""
    lines = text.splitlines()
    heads = [(i, m) for i, line in enumerate(lines) if (m := BUG_HEADING.match(line))]
    items: list[Item] = []
    problems: list[str] = []
    for k, (i, m) in enumerate(heads):
        bug_id, title = m.group(1), m.group(2)
        end = heads[k + 1][0] if k + 1 < len(heads) else len(lines)
        body = lines[i:end]
        if any(BUG_CLOSED.match(b) for b in body):
            continue
        found = _fields_under(lines, i)
        where = f"BUGS.md line {i + 1}"
        if not found:
            problems.append(
                f"{where}: {bug_id} is not marked FIXED and carries no metadata. "
                "An open bug needs Id, Category, Gives and Priority so it appears in the index."
            )
            continue
        if not _validate(found, where, bug_id, problems):
            continue
        if found["Id"] != bug_id:
            problems.append(f"{where}: {bug_id} declares Id {found['Id']!r}; they must match")
            continue
        items.append(
            Item("bugs", i + 1, bug_id, "BUG", title, found["Category"], _collapse(found["Gives"]), found["Priority"])
        )
    return items, problems


def parse_all() -> tuple[list[Item], list[str]]:
    items, problems = parse_backlog(BACKLOG.read_text(encoding="utf-8"))
    if BUGS.exists():
        b_items, b_problems = parse_bugs(BUGS.read_text(encoding="utf-8"))
        items += b_items
        problems += b_problems
    seen: dict[str, Item] = {}
    for it in items:
        if it.ident in seen:
            problems.append(f"duplicate Id {it.ident!r}: {seen[it.ident].source} and {it.source}")
        seen[it.ident] = it
    return items, problems


def render(items: list[Item]) -> str:
    """The table, ordered by priority then category then id. Impact first, never cost."""
    order = {p: n for n, p in enumerate(PRIORITIES)}
    rows = sorted(items, key=lambda it: (order.get(it.priority, 99), it.category, it.ident))
    bugs = sum(1 for it in rows if it.source == "bugs")
    out = [
        BEGIN,
        "",
        f"**Open actions: {len(rows)}** ({len(rows) - bugs} from this file, {bugs} open bugs from `BUGS.md`).",
        "Generated — edit the fields under each heading, not this table.",
        "",
        "| Id | P | Category | Action | What it gives |",
        "|---|---|---|---|---|",
    ]
    for it in rows:
        title = _collapse(it.title).replace("|", "\\|")
        gives = it.gives.replace("|", "\\|")
        out.append(f"| {it.ident} | {it.priority} | {it.category} | {title} | {gives} |")
    out += ["", END]
    return "\n".join(out)


def replace_block(text: str, block: str) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{BACKLOG.name}: missing the index markers; add {BEGIN} and {END}")
    return text[:start] + block + text[end + len(END) :]


def next_free_id() -> str:
    """The lowest unused B-nnn, scanning the whole FILE rather than the open items.

    An id is a permanent handle and must never be reused, so a closed item's id is still taken. A
    first version derived this from the parsed OPEN items only, and the moment B-007 was closed it
    offered B-007 again — which would have made every citation of the closed item resolve to a
    different one.
    """
    text = BACKLOG.read_text(encoding="utf-8")
    if BUGS.exists():
        text += BUGS.read_text(encoding="utf-8")
    used = {int(m) for m in re.findall(r"\*\*Id:\*\*\s*B-(\d{3})", text)}
    n = 1
    while n in used:
        n += 1
    return f"B-{n:03d}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if stale or a field is missing")
    args = ap.parse_args()

    items, problems = parse_all()
    if problems:
        print(f"{len(problems)} problem(s)")
        for p in problems:
            print(f"  {p}")
        print("\nEvery open item needs Id, Category, Gives and Priority directly under its heading.")
        print("See 'How to read this file' in BACKLOG.md.")
        return 1
    if not items:
        print("no actionable items found — that is almost certainly a parse bug")
        return 1

    text = BACKLOG.read_text(encoding="utf-8")
    updated = replace_block(text, render(items))
    if args.check:
        if updated != text:
            print("STALE: the index does not match the item fields. Run scripts/backlog_index.py")
            return 1
        print(f"up to date: {len(items)} open action(s)")
        return 0

    BACKLOG.write_text(updated, encoding="utf-8", newline="\n")
    print(f"wrote {BACKLOG.name} index ({len(items)} open actions)")
    for p in PRIORITIES:
        print(f"  {p}: {sum(1 for it in items if it.priority == p)}")
    print(f"  next free backlog id: {next_free_id()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
