"""Generate and validate the summary table at the top of BACKLOG.md.

Why this exists rather than a hand-maintained table: the file had sixteen rounds of numbered
lists and the same items kept recurring, because it recorded WHAT to do and never what doing it
would buy. The cheapest item won every time. On 2026-09-21 a session proposed a guard-tolerance
fix that changes zero coached turns ahead of a defect affecting forty.

So every actionable item carries three fields and this script is the thing that will not let
them be omitted. Two entry points, deliberately the same shape as `metrics_history.py` and
`snapshot_clauses.py`, which already work this way in this repo:

    python scripts/backlog_index.py            # rewrite the table in place
    python scripts/backlog_index.py --check     # exit 1 if the table is stale or a field is missing

The table is GENERATED from the per-item fields rather than maintained beside them. Writing it
twice is the "two copies of one check handed different arguments" shape that caused four defects
in this repo, so there is one source: the fields under each heading.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

BACKLOG = Path(__file__).resolve().parent.parent / "BACKLOG.md"

BEGIN = "<!-- BEGIN BACKLOG INDEX (generated by scripts/backlog_index.py - do not edit by hand) -->"
END = "<!-- END BACKLOG INDEX -->"

#: A heading is ACTIONABLE when it starts with one of these. Everything else in the file is a
#: record — a closed item, a decision kept for its reasoning, a narrative section — and records
#: do not get priorities. Em dash or hyphen, because both have been used.
ACTIONABLE = re.compile(r"^(#{2,3})\s+(TOP|OPEN)\s*[—-]\s*(.+?)\s*$")

#: Any heading at all, so a field block cannot be read across a heading boundary.
ANY_HEADING = re.compile(r"^#{1,6}\s+")

CATEGORIES = ("coaching", "instrumentation", "engine", "decision", "infra")
PRIORITIES = ("P1", "P2", "P3")

FIELD = re.compile(r"^\s*-\s+\*\*(Category|Gives|Priority):\*\*\s*(.+?)\s*$")


@dataclass(frozen=True)
class Item:
    line: int
    kind: str  # TOP or OPEN
    title: str
    category: str
    gives: str
    priority: str


def _collapse(text: str) -> str:
    """One line, single-spaced — a table cell cannot contain a newline."""
    return " ".join(text.split())


def parse(text: str) -> tuple[list[Item], list[str]]:
    """``(items, problems)``. Never raises on a malformed file: the caller reports."""
    lines = text.splitlines()
    items: list[Item] = []
    problems: list[str] = []

    for i, line in enumerate(lines):
        m = ACTIONABLE.match(line)
        if not m:
            continue
        kind, title = m.group(2), m.group(3)

        # Fields must sit in the block directly under the heading, before any prose that is not
        # a field and before the next heading. Continuation lines of a field are indented, so a
        # field's value may span lines; that is why `pending` exists.
        found: dict[str, str] = {}
        pending: str | None = None
        for raw in lines[i + 1 :]:
            if ANY_HEADING.match(raw):
                break
            fm = FIELD.match(raw)
            if fm:
                pending = fm.group(1)
                found[pending] = fm.group(2)
                continue
            if pending and raw.startswith("  ") and raw.strip():
                found[pending] += " " + raw.strip()
                continue
            if raw.strip():
                # First non-field prose ends the block. Without this a "**Gives:**" appearing
                # later in the body would be picked up as the item's own field.
                break

        missing = [f for f in ("Category", "Gives", "Priority") if f not in found]
        if missing:
            problems.append(f"line {i + 1}: {kind} — {title!r} is missing {', '.join(missing)}")
            continue

        category, gives, priority = found["Category"], _collapse(found["Gives"]), found["Priority"]
        if category not in CATEGORIES:
            problems.append(f"line {i + 1}: {title!r} has Category {category!r}, expected one of {CATEGORIES}")
        if priority not in PRIORITIES:
            problems.append(f"line {i + 1}: {title!r} has Priority {priority!r}, expected one of {PRIORITIES}")
        items.append(Item(i + 1, kind, title, category, gives, priority))

    return items, problems


def render(items: list[Item]) -> str:
    """The table, ordered by priority then category then file order.

    Sorted by IMPACT, which is what the priority encodes — never by cost, and never by where the
    item happens to sit in a 3000-line file.
    """
    order = {p: n for n, p in enumerate(PRIORITIES)}
    rows = sorted(items, key=lambda it: (order.get(it.priority, 99), it.category, it.line))
    out = [
        BEGIN,
        "",
        f"**Open actions: {len(rows)}.** Generated — edit the fields under each heading, not this table.",
        "",
        "| P | Category | Action | What it gives |",
        "|---|---|---|---|",
    ]
    for it in rows:
        title = _collapse(it.title).replace("|", "\\|")
        gives = it.gives.replace("|", "\\|")
        out.append(f"| {it.priority} | {it.category} | {title} | {gives} |")
    out += ["", END]
    return "\n".join(out)


def replace_block(text: str, block: str) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"{BACKLOG.name}: missing the index markers; add {BEGIN} and {END}")
    return text[:start] + block + text[end + len(END) :]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if stale or a field is missing")
    ap.add_argument("--path", default=str(BACKLOG))
    args = ap.parse_args()

    path = Path(args.path)
    text = path.read_text(encoding="utf-8")
    items, problems = parse(text)

    if problems:
        print(f"{path.name}: {len(problems)} problem(s)")
        for p in problems:
            print(f"  {p}")
        print("\nEvery TOP/OPEN heading needs Category, Gives and Priority directly under it.")
        print("See 'How to read this file' in BACKLOG.md.")
        return 1

    if not items:
        print(f"{path.name}: no actionable items found — that is almost certainly a parse bug")
        return 1

    updated = replace_block(text, render(items))
    if args.check:
        if updated != text:
            print(f"STALE: {path.name} index does not match the item fields. Run scripts/backlog_index.py")
            return 1
        print(f"up to date: {len(items)} open action(s)")
        return 0

    path.write_text(updated, encoding="utf-8", newline="\n")
    print(f"wrote {path.name} index ({len(items)} open actions)")
    for p in PRIORITIES:
        n = sum(1 for it in items if it.priority == p)
        print(f"  {p}: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
